### ISSUE TITLE
有没有考虑linux版本的脚本实现

### ISSUE THREAD

**Issue by shaojava** [Hzllaga/BT_Panel_Privilege_Escalation#1]
有没有考虑linux版本的脚本实现

**Comment by Hzllaga** [comment]
脚本代码基本上一样的，我这里没特别指出Linux只是因为宝塔在Windows版本对于目录权限的控管没那么严格，相对容易而已；宝塔Linux不太有机会去读到那些目录的。

**Comment by shaojava** [comment]
只能是一个思路吧。测试发现宝塔的版本不同密码的加密方式也不一样。
而且登录验证也是不一样的
